/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AreaDto {
  'id' : bigint,
  'name' : string,
  'districtId' : bigint,
  'isAssigned' : boolean,
}
export interface AreaManagerDto {
  'id' : bigint,
  'status' : AreaManagerStatus,
  'contact' : string,
  'username' : string,
  'districtId' : bigint,
  'areaId' : bigint,
  'passwordHash' : string,
}
export type AreaManagerStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BloodRequestDto {
  'id' : bigint,
  'age' : bigint,
  'status' : BloodRequestStatus,
  'contact' : string,
  'operationDate' : string,
  'createdAt' : bigint,
  'toId' : bigint,
  'hospitalAddress' : string,
  'toRole' : string,
  'bloodGroup' : string,
  'fromRole' : string,
  'patientName' : string,
  'altContact' : [] | [string],
  'attenderName' : string,
  'fromId' : bigint,
  'hospitalName' : string,
}
export type BloodRequestStatus = { 'forwarded' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface DistrictDto {
  'id' : bigint,
  'name' : string,
  'isAssigned' : boolean,
}
export interface DistrictManagerDto {
  'id' : bigint,
  'status' : DistrictManagerStatus,
  'contact' : string,
  'username' : string,
  'districtId' : bigint,
  'passwordHash' : string,
}
export type DistrictManagerStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DonorDto {
  'id' : bigint,
  'age' : bigint,
  'status' : DonorStatus,
  'contact' : string,
  'appointedAt' : [] | [bigint],
  'name' : string,
  'districtId' : bigint,
  'rejectedAt' : [] | [bigint],
  'bloodGroup' : IDL.Text,
  'lastDonatedDate' : [] | [bigint],
  'patientName' : [] | [string],
  'areaId' : bigint,
  'areaManagerId' : bigint,
  'tempRejectedUntil' : [] | [bigint],
  'tempRejectedReason' : [] | [string],
}
export type DonorStatus = { 'appointed' : null } |
  { 'tempRejected' : null } |
  { 'available' : null } |
  { 'permRejected' : null };
export interface NoticeDto {
  'id' : bigint,
  'createdAt' : bigint,
  'toId' : [] | [bigint],
  'toRole' : string,
  'message' : string,
  'fromRole' : string,
  'fromId' : bigint,
}
export interface UserDto {
  'id' : bigint,
  'contact' : string,
  'username' : string,
  'districtId' : bigint,
  'passwordHash' : string,
}
export interface UserProfile {
  'amId' : [] | [bigint],
  'userId' : [] | [bigint],
  'dmId' : [] | [bigint],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonor' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, [] | [bigint], bigint],
    DonorDto
  >,
  'approveAreaManager' : ActorMethod<[bigint, bigint], AreaManagerDto>,
  'approveDistrictManager' : ActorMethod<[bigint], DistrictManagerDto>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeBloodRequest' : ActorMethod<[bigint], BloodRequestDto>,
  'createArea' : ActorMethod<[bigint, bigint, string], AreaDto>,
  'createBloodRequest' : ActorMethod<
    [
      string,
      bigint,
      string,
      bigint,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
    ],
    BloodRequestDto
  >,
  'createDistrict' : ActorMethod<[string], DistrictDto>,
  'deleteAreaManager' : ActorMethod<[bigint, bigint], undefined>,
  'deleteDistrictManager' : ActorMethod<[bigint], undefined>,
  'deleteDonor' : ActorMethod<[bigint], undefined>,
  'forwardBloodRequest' : ActorMethod<
    [bigint, string, bigint],
    BloodRequestDto
  >,
  'getApprovedAreaManagersByDistrict' : ActorMethod<
    [bigint],
    Array<AreaManagerDto>
  >,
  'getApprovedDistrictManagers' : ActorMethod<[], Array<DistrictManagerDto>>,
  'getArea' : ActorMethod<[bigint], AreaDto>,
  'getAreaManager' : ActorMethod<[bigint], AreaManagerDto>,
  'getAreasByDistrict' : ActorMethod<[bigint], Array<AreaDto>>,
  'getBloodRequestsForRecipient' : ActorMethod<
    [string, bigint],
    Array<BloodRequestDto>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDistrict' : ActorMethod<[bigint], DistrictDto>,
  'getDistrictManager' : ActorMethod<[bigint], DistrictManagerDto>,
  'getDistricts' : ActorMethod<[], Array<DistrictDto>>,
  'getDonorsByArea' : ActorMethod<[bigint], Array<DonorDto>>,
  'getNoticesForRecipient' : ActorMethod<[string, bigint], Array<NoticeDto>>,
  'getPendingAreaManagersForDistrict' : ActorMethod<
    [bigint],
    Array<AreaManagerDto>
  >,
  'getPendingDistrictManagers' : ActorMethod<[], Array<DistrictManagerDto>>,
  'getUser' : ActorMethod<[bigint], UserDto>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAreaManager' : ActorMethod<
    [string, string, string, bigint, bigint],
    AreaManagerDto
  >,
  'registerDistrictManager' : ActorMethod<
    [string, string, string, bigint],
    DistrictManagerDto
  >,
  'registerUser' : ActorMethod<[string, string, string, bigint], UserDto>,
  'rejectAreaManager' : ActorMethod<[bigint, bigint], AreaManagerDto>,
  'rejectDistrictManager' : ActorMethod<[bigint], DistrictManagerDto>,
  'restoreDonor' : ActorMethod<[bigint], DonorDto>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendNotice' : ActorMethod<
    [string, bigint, string, [] | [bigint], string],
    NoticeDto
  >,
  'updateDonorStatus' : ActorMethod<
    [bigint, DonorStatus, [] | [bigint], [] | [bigint], [] | [string], [] | [bigint], [] | [string]],
    DonorDto
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
