/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonorStatus = IDL.Variant({
  'appointed' : IDL.Null,
  'tempRejected' : IDL.Null,
  'available' : IDL.Null,
  'permRejected' : IDL.Null,
});
export const DonorDto = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'status' : DonorStatus,
  'contact' : IDL.Text,
  'appointedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'districtId' : IDL.Nat,
  'rejectedAt' : IDL.Opt(IDL.Int),
  'bloodGroup' : IDL.Text,
  'lastDonatedDate' : IDL.Opt(IDL.Int),
  'patientName' : IDL.Opt(IDL.Text),
  'areaId' : IDL.Nat,
  'areaManagerId' : IDL.Nat,
  'tempRejectedUntil' : IDL.Opt(IDL.Int),
  'tempRejectedReason' : IDL.Opt(IDL.Text),
});
export const AreaManagerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AreaManagerDto = IDL.Record({
  'id' : IDL.Nat,
  'status' : AreaManagerStatus,
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'districtId' : IDL.Nat,
  'areaId' : IDL.Nat,
  'passwordHash' : IDL.Text,
});
export const DistrictManagerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DistrictManagerDto = IDL.Record({
  'id' : IDL.Nat,
  'status' : DistrictManagerStatus,
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'districtId' : IDL.Nat,
  'passwordHash' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodRequestStatus = IDL.Variant({
  'forwarded' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const BloodRequestDto = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'status' : BloodRequestStatus,
  'contact' : IDL.Text,
  'operationDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'toId' : IDL.Nat,
  'hospitalAddress' : IDL.Text,
  'toRole' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'fromRole' : IDL.Text,
  'patientName' : IDL.Text,
  'altContact' : IDL.Opt(IDL.Text),
  'attenderName' : IDL.Text,
  'fromId' : IDL.Nat,
  'hospitalName' : IDL.Text,
});
export const AreaDto = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'districtId' : IDL.Nat,
  'isAssigned' : IDL.Bool,
});
export const DistrictDto = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAssigned' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'amId' : IDL.Opt(IDL.Nat),
  'userId' : IDL.Opt(IDL.Nat),
  'dmId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const NoticeDto = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'toId' : IDL.Opt(IDL.Nat),
  'toRole' : IDL.Text,
  'message' : IDL.Text,
  'fromRole' : IDL.Text,
  'fromId' : IDL.Nat,
});
export const UserDto = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'districtId' : IDL.Nat,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Int),
        IDL.Nat,
      ],
      [DonorDto],
      [],
    ),
  'approveAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [AreaManagerDto], []),
  'approveDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeBloodRequest' : IDL.Func([IDL.Nat], [BloodRequestDto], []),
  'createArea' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [AreaDto], []),
  'createBloodRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [BloodRequestDto],
      [],
    ),
  'createDistrict' : IDL.Func([IDL.Text], [DistrictDto], []),
  'deleteAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteDistrictManager' : IDL.Func([IDL.Nat], [], []),
  'deleteDonor' : IDL.Func([IDL.Nat], [], []),
  'forwardBloodRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [BloodRequestDto],
      [],
    ),
  'getApprovedAreaManagersByDistrict' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AreaManagerDto)],
      ['query'],
    ),
  'getApprovedDistrictManagers' : IDL.Func(
      [],
      [IDL.Vec(DistrictManagerDto)],
      ['query'],
    ),
  'getArea' : IDL.Func([IDL.Nat], [AreaDto], ['query']),
  'getAreaManager' : IDL.Func([IDL.Nat], [AreaManagerDto], ['query']),
  'getAreasByDistrict' : IDL.Func([IDL.Nat], [IDL.Vec(AreaDto)], ['query']),
  'getBloodRequestsForRecipient' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(BloodRequestDto)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDistrict' : IDL.Func([IDL.Nat], [DistrictDto], ['query']),
  'getDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], ['query']),
  'getDistricts' : IDL.Func([], [IDL.Vec(DistrictDto)], ['query']),
  'getDonorsByArea' : IDL.Func([IDL.Nat], [IDL.Vec(DonorDto)], ['query']),
  'getNoticesForRecipient' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(NoticeDto)],
      ['query'],
    ),
  'getPendingAreaManagersForDistrict' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AreaManagerDto)],
      ['query'],
    ),
  'getPendingDistrictManagers' : IDL.Func(
      [],
      [IDL.Vec(DistrictManagerDto)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [UserDto], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAreaManager' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [AreaManagerDto],
      [],
    ),
  'registerDistrictManager' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [DistrictManagerDto],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [UserDto],
      [],
    ),
  'rejectAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [AreaManagerDto], []),
  'rejectDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], []),
  'restoreDonor' : IDL.Func([IDL.Nat], [DonorDto], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendNotice' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [NoticeDto],
      [],
    ),
  'updateDonorStatus' : IDL.Func(
      [
        IDL.Nat,
        DonorStatus,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [DonorDto],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonorStatus = IDL.Variant({
    'appointed' : IDL.Null,
    'tempRejected' : IDL.Null,
    'available' : IDL.Null,
    'permRejected' : IDL.Null,
  });
  const DonorDto = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'status' : DonorStatus,
    'contact' : IDL.Text,
    'appointedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'districtId' : IDL.Nat,
    'rejectedAt' : IDL.Opt(IDL.Int),
    'bloodGroup' : IDL.Text,
    'lastDonatedDate' : IDL.Opt(IDL.Int),
    'patientName' : IDL.Opt(IDL.Text),
    'areaId' : IDL.Nat,
    'areaManagerId' : IDL.Nat,
    'tempRejectedUntil' : IDL.Opt(IDL.Int),
    'tempRejectedReason' : IDL.Opt(IDL.Text),
  });
  const AreaManagerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AreaManagerDto = IDL.Record({
    'id' : IDL.Nat,
    'status' : AreaManagerStatus,
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'districtId' : IDL.Nat,
    'areaId' : IDL.Nat,
    'passwordHash' : IDL.Text,
  });
  const DistrictManagerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DistrictManagerDto = IDL.Record({
    'id' : IDL.Nat,
    'status' : DistrictManagerStatus,
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'districtId' : IDL.Nat,
    'passwordHash' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodRequestStatus = IDL.Variant({
    'forwarded' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const BloodRequestDto = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'status' : BloodRequestStatus,
    'contact' : IDL.Text,
    'operationDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'toId' : IDL.Nat,
    'hospitalAddress' : IDL.Text,
    'toRole' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'fromRole' : IDL.Text,
    'patientName' : IDL.Text,
    'altContact' : IDL.Opt(IDL.Text),
    'attenderName' : IDL.Text,
    'fromId' : IDL.Nat,
    'hospitalName' : IDL.Text,
  });
  const AreaDto = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'districtId' : IDL.Nat,
    'isAssigned' : IDL.Bool,
  });
  const DistrictDto = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAssigned' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'amId' : IDL.Opt(IDL.Nat),
    'userId' : IDL.Opt(IDL.Nat),
    'dmId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const NoticeDto = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'toId' : IDL.Opt(IDL.Nat),
    'toRole' : IDL.Text,
    'message' : IDL.Text,
    'fromRole' : IDL.Text,
    'fromId' : IDL.Nat,
  });
  const UserDto = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'districtId' : IDL.Nat,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Int),
          IDL.Nat,
        ],
        [DonorDto],
        [],
      ),
    'approveAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [AreaManagerDto], []),
    'approveDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeBloodRequest' : IDL.Func([IDL.Nat], [BloodRequestDto], []),
    'createArea' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [AreaDto], []),
    'createBloodRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [BloodRequestDto],
        [],
      ),
    'createDistrict' : IDL.Func([IDL.Text], [DistrictDto], []),
    'deleteAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteDistrictManager' : IDL.Func([IDL.Nat], [], []),
    'deleteDonor' : IDL.Func([IDL.Nat], [], []),
    'forwardBloodRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [BloodRequestDto],
        [],
      ),
    'getApprovedAreaManagersByDistrict' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AreaManagerDto)],
        ['query'],
      ),
    'getApprovedDistrictManagers' : IDL.Func(
        [],
        [IDL.Vec(DistrictManagerDto)],
        ['query'],
      ),
    'getArea' : IDL.Func([IDL.Nat], [AreaDto], ['query']),
    'getAreaManager' : IDL.Func([IDL.Nat], [AreaManagerDto], ['query']),
    'getAreasByDistrict' : IDL.Func([IDL.Nat], [IDL.Vec(AreaDto)], ['query']),
    'getBloodRequestsForRecipient' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(BloodRequestDto)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDistrict' : IDL.Func([IDL.Nat], [DistrictDto], ['query']),
    'getDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], ['query']),
    'getDistricts' : IDL.Func([], [IDL.Vec(DistrictDto)], ['query']),
    'getDonorsByArea' : IDL.Func([IDL.Nat], [IDL.Vec(DonorDto)], ['query']),
    'getNoticesForRecipient' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(NoticeDto)],
        ['query'],
      ),
    'getPendingAreaManagersForDistrict' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AreaManagerDto)],
        ['query'],
      ),
    'getPendingDistrictManagers' : IDL.Func(
        [],
        [IDL.Vec(DistrictManagerDto)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [UserDto], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAreaManager' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [AreaManagerDto],
        [],
      ),
    'registerDistrictManager' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [DistrictManagerDto],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [UserDto],
        [],
      ),
    'rejectAreaManager' : IDL.Func([IDL.Nat, IDL.Nat], [AreaManagerDto], []),
    'rejectDistrictManager' : IDL.Func([IDL.Nat], [DistrictManagerDto], []),
    'restoreDonor' : IDL.Func([IDL.Nat], [DonorDto], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendNotice' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [NoticeDto],
        [],
      ),
    'updateDonorStatus' : IDL.Func(
        [
          IDL.Nat,
          DonorStatus,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [DonorDto],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
