/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AreaDto {
    id: bigint;
    name: string;
    districtId: bigint;
    isAssigned: boolean;
}
export interface DistrictDto {
    id: bigint;
    name: string;
    isAssigned: boolean;
}
export interface UserDto {
    id: bigint;
    contact: string;
    username: string;
    districtId: bigint;
    passwordHash: string;
}
export interface AreaManagerDto {
    id: bigint;
    status: AreaManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    areaId: bigint;
    passwordHash: string;
}
export interface DistrictManagerDto {
    id: bigint;
    status: DistrictManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    passwordHash: string;
}
export interface BloodRequestDto {
    id: bigint;
    age: bigint;
    status: BloodRequestStatus;
    contact: string;
    operationDate: string;
    createdAt: bigint;
    toId: bigint;
    hospitalAddress: string;
    toRole: string;
    bloodGroup: string;
    fromRole: string;
    patientName: string;
    altContact?: string;
    attenderName: string;
    fromId: bigint;
    hospitalName: string;
}
export interface DonorDto {
    id: bigint;
    age: bigint;
    status: DonorStatus;
    contact: string;
    appointedAt?: bigint;
    name: string;
    districtId: bigint;
    rejectedAt?: bigint;
    bloodGroup: string;
    lastDonatedDate?: bigint;
    patientName?: string;
    areaId: bigint;
    areaManagerId: bigint;
    tempRejectedUntil?: bigint;
    tempRejectedReason?: string;
}
export interface NoticeDto {
    id: bigint;
    createdAt: bigint;
    toId?: bigint;
    toRole: string;
    message: string;
    fromRole: string;
    fromId: bigint;
}
export interface UserProfile {
    amId?: bigint;
    userId?: bigint;
    dmId?: bigint;
    name: string;
    role: string;
}
export enum BloodRequestStatus {
    forwarded = "forwarded",
    pending = "pending",
    completed = "completed"
}
export enum DistrictManagerStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DonorStatus {
    appointed = "appointed",
    tempRejected = "tempRejected",
    available = "available",
    permRejected = "permRejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonor(name: string, contact: string, bloodGroup: string, districtId: bigint, areaId: bigint, age: bigint, lastDonatedDate: bigint | null, areaManagerId: bigint): Promise<DonorDto>;
    approveAreaManager(dmId: bigint, amId: bigint): Promise<AreaManagerDto>;
    approveDistrictManager(dmId: bigint): Promise<DistrictManagerDto>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeBloodRequest(requestId: bigint): Promise<BloodRequestDto>;
    createArea(dmId: bigint, districtId: bigint, name: string): Promise<AreaDto>;
    createBloodRequest(fromRole: string, fromId: bigint, toRole: string, toId: bigint, patientName: string, age: bigint, bloodGroup: string, hospitalName: string, hospitalAddress: string, attenderName: string, contact: string, altContact: string | null, operationDate: string): Promise<BloodRequestDto>;
    createDistrict(name: string): Promise<DistrictDto>;
    deleteAreaManager(dmId: bigint, amId: bigint): Promise<void>;
    deleteDistrictManager(dmId: bigint): Promise<void>;
    deleteDonor(donorId: bigint): Promise<void>;
    forwardBloodRequest(requestId: bigint, toRole: string, toId: bigint): Promise<BloodRequestDto>;
    getApprovedAreaManagersByDistrict(districtId: bigint): Promise<Array<AreaManagerDto>>;
    getApprovedDistrictManagers(): Promise<Array<DistrictManagerDto>>;
    getArea(id: bigint): Promise<AreaDto>;
    getAreaManager(amId: bigint): Promise<AreaManagerDto>;
    getAreasByDistrict(districtId: bigint): Promise<Array<AreaDto>>;
    getBloodRequestsForRecipient(toRole: string, toId: bigint): Promise<Array<BloodRequestDto>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDistrict(id: bigint): Promise<DistrictDto>;
    getDistrictManager(dmId: bigint): Promise<DistrictManagerDto>;
    getDistricts(): Promise<Array<DistrictDto>>;
    getDonorsByArea(areaId: bigint): Promise<Array<DonorDto>>;
    getNoticesForRecipient(role: string, id: bigint): Promise<Array<NoticeDto>>;
    getPendingAreaManagersForDistrict(districtId: bigint): Promise<Array<AreaManagerDto>>;
    getPendingDistrictManagers(): Promise<Array<DistrictManagerDto>>;
    getUser(userId: bigint): Promise<UserDto>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerAreaManager(username: string, contact: string, passwordHash: string, districtId: bigint, areaId: bigint): Promise<AreaManagerDto>;
    registerDistrictManager(username: string, contact: string, passwordHash: string, districtId: bigint): Promise<DistrictManagerDto>;
    registerUser(username: string, contact: string, passwordHash: string, districtId: bigint): Promise<UserDto>;
    rejectAreaManager(dmId: bigint, amId: bigint): Promise<AreaManagerDto>;
    rejectDistrictManager(dmId: bigint): Promise<DistrictManagerDto>;
    restoreDonor(donorId: bigint): Promise<DonorDto>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendNotice(fromRole: string, fromId: bigint, toRole: string, toId: bigint | null, message: string): Promise<NoticeDto>;
    updateDonorStatus(donorId: bigint, status: DonorStatus, rejectedAt: bigint | null, appointedAt: bigint | null, patientName: string | null, tempRejectedUntil: bigint | null, tempRejectedReason: string | null): Promise<DonorDto>;
}
import type { AreaManagerDto as _AreaManagerDto, AreaManagerStatus as _AreaManagerStatus, BloodRequestDto as _BloodRequestDto, BloodRequestStatus as _BloodRequestStatus, DistrictManagerDto as _DistrictManagerDto, DistrictManagerStatus as _DistrictManagerStatus, DonorDto as _DonorDto, DonorStatus as _DonorStatus, NoticeDto as _NoticeDto, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonor(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint | null, arg7: bigint): Promise<DonorDto> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonor(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonor(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveAreaManager(arg0: bigint, arg1: bigint): Promise<AreaManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAreaManager(arg0, arg1);
                return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAreaManager(arg0, arg1);
            return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveDistrictManager(arg0: bigint): Promise<DistrictManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDistrictManager(arg0);
                return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDistrictManager(arg0);
            return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeBloodRequest(arg0: bigint): Promise<BloodRequestDto> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBloodRequest(arg0);
                return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBloodRequest(arg0);
            return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArea(arg0: bigint, arg1: bigint, arg2: string): Promise<AreaDto> {
        if (this.processError) {
            try {
                const result = await this.actor.createArea(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArea(arg0, arg1, arg2);
            return result;
        }
    }
    async createBloodRequest(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string | null, arg12: string): Promise<BloodRequestDto> {
        if (this.processError) {
            try {
                const result = await this.actor.createBloodRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg11), arg12);
                return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBloodRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg11), arg12);
            return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDistrict(arg0: string): Promise<DistrictDto> {
        if (this.processError) {
            try {
                const result = await this.actor.createDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDistrict(arg0);
            return result;
        }
    }
    async deleteAreaManager(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAreaManager(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAreaManager(arg0, arg1);
            return result;
        }
    }
    async deleteDistrictManager(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDistrictManager(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDistrictManager(arg0);
            return result;
        }
    }
    async deleteDonor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonor(arg0);
            return result;
        }
    }
    async forwardBloodRequest(arg0: bigint, arg1: string, arg2: bigint): Promise<BloodRequestDto> {
        if (this.processError) {
            try {
                const result = await this.actor.forwardBloodRequest(arg0, arg1, arg2);
                return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forwardBloodRequest(arg0, arg1, arg2);
            return from_candid_BloodRequestDto_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedAreaManagersByDistrict(arg0: bigint): Promise<Array<AreaManagerDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedAreaManagersByDistrict(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedAreaManagersByDistrict(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedDistrictManagers(): Promise<Array<DistrictManagerDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedDistrictManagers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedDistrictManagers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArea(arg0: bigint): Promise<AreaDto> {
        if (this.processError) {
            try {
                const result = await this.actor.getArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArea(arg0);
            return result;
        }
    }
    async getAreaManager(arg0: bigint): Promise<AreaManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreaManager(arg0);
                return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreaManager(arg0);
            return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAreasByDistrict(arg0: bigint): Promise<Array<AreaDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreasByDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreasByDistrict(arg0);
            return result;
        }
    }
    async getBloodRequestsForRecipient(arg0: string, arg1: bigint): Promise<Array<BloodRequestDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodRequestsForRecipient(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodRequestsForRecipient(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistrict(arg0: bigint): Promise<DistrictDto> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistrict(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistrict(arg0);
            return result;
        }
    }
    async getDistrictManager(arg0: bigint): Promise<DistrictManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistrictManager(arg0);
                return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistrictManager(arg0);
            return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistricts(): Promise<Array<DistrictDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistricts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistricts();
            return result;
        }
    }
    async getDonorsByArea(arg0: bigint): Promise<Array<DonorDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorsByArea(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorsByArea(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoticesForRecipient(arg0: string, arg1: bigint): Promise<Array<NoticeDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticesForRecipient(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticesForRecipient(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingAreaManagersForDistrict(arg0: bigint): Promise<Array<AreaManagerDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingAreaManagersForDistrict(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingAreaManagersForDistrict(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDistrictManagers(): Promise<Array<DistrictManagerDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDistrictManagers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDistrictManagers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: bigint): Promise<UserDto> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerAreaManager(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<AreaManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAreaManager(arg0, arg1, arg2, arg3, arg4);
                return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAreaManager(arg0, arg1, arg2, arg3, arg4);
            return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerDistrictManager(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<DistrictManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDistrictManager(arg0, arg1, arg2, arg3);
                return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDistrictManager(arg0, arg1, arg2, arg3);
            return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<UserDto> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectAreaManager(arg0: bigint, arg1: bigint): Promise<AreaManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAreaManager(arg0, arg1);
                return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAreaManager(arg0, arg1);
            return from_candid_AreaManagerDto_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectDistrictManager(arg0: bigint): Promise<DistrictManagerDto> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDistrictManager(arg0);
                return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDistrictManager(arg0);
            return from_candid_DistrictManagerDto_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreDonor(arg0: bigint): Promise<DonorDto> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreDonor(arg0);
                return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreDonor(arg0);
            return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendNotice(arg0: string, arg1: bigint, arg2: string, arg3: bigint | null, arg4: string): Promise<NoticeDto> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotice(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_NoticeDto_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotice(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_NoticeDto_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonorStatus(arg0: bigint, arg1: DonorStatus, arg2: bigint | null, arg3: bigint | null, arg4: string | null, arg5: bigint | null, arg6: string | null): Promise<DonorDto> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonorStatus(arg0, to_candid_DonorStatus_n38(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6));
                return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonorStatus(arg0, to_candid_DonorStatus_n38(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg6));
            return from_candid_DonorDto_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AreaManagerDto_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AreaManagerDto): AreaManagerDto {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AreaManagerStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AreaManagerStatus): AreaManagerStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BloodRequestDto_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequestDto): BloodRequestDto {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BloodRequestStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequestStatus): BloodRequestStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DistrictManagerDto_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistrictManagerDto): DistrictManagerDto {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DistrictManagerStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistrictManagerStatus): DistrictManagerStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DonorDto_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorDto): DonorDto {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DonorStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorStatus): DonorStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeDto_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeDto): NoticeDto {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DistrictManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    passwordHash: string;
}): {
    id: bigint;
    status: DistrictManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    passwordHash: string;
} {
    return {
        id: value.id,
        status: from_candid_DistrictManagerStatus_n14(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        username: value.username,
        districtId: value.districtId,
        passwordHash: value.passwordHash
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    status: _BloodRequestStatus;
    contact: string;
    operationDate: string;
    createdAt: bigint;
    toId: bigint;
    hospitalAddress: string;
    toRole: string;
    bloodGroup: string;
    fromRole: string;
    patientName: string;
    altContact: [] | [string];
    attenderName: string;
    fromId: bigint;
    hospitalName: string;
}): {
    id: bigint;
    age: bigint;
    status: BloodRequestStatus;
    contact: string;
    operationDate: string;
    createdAt: bigint;
    toId: bigint;
    hospitalAddress: string;
    toRole: string;
    bloodGroup: string;
    fromRole: string;
    patientName: string;
    altContact?: string;
    attenderName: string;
    fromId: bigint;
    hospitalName: string;
} {
    return {
        id: value.id,
        age: value.age,
        status: from_candid_BloodRequestStatus_n19(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        operationDate: value.operationDate,
        createdAt: value.createdAt,
        toId: value.toId,
        hospitalAddress: value.hospitalAddress,
        toRole: value.toRole,
        bloodGroup: value.bloodGroup,
        fromRole: value.fromRole,
        patientName: value.patientName,
        altContact: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.altContact)),
        attenderName: value.attenderName,
        fromId: value.fromId,
        hospitalName: value.hospitalName
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amId: [] | [bigint];
    userId: [] | [bigint];
    dmId: [] | [bigint];
    name: string;
    role: string;
}): {
    amId?: bigint;
    userId?: bigint;
    dmId?: bigint;
    name: string;
    role: string;
} {
    return {
        amId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.amId)),
        userId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.userId)),
        dmId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.dmId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    status: _DonorStatus;
    contact: string;
    appointedAt: [] | [bigint];
    name: string;
    districtId: bigint;
    rejectedAt: [] | [bigint];
    bloodGroup: string;
    lastDonatedDate: [] | [bigint];
    patientName: [] | [string];
    areaId: bigint;
    areaManagerId: bigint;
}): {
    id: bigint;
    age: bigint;
    status: DonorStatus;
    contact: string;
    appointedAt?: bigint;
    name: string;
    districtId: bigint;
    rejectedAt?: bigint;
    bloodGroup: string;
    lastDonatedDate?: bigint;
    patientName?: string;
    areaId: bigint;
    areaManagerId: bigint;
} {
    return {
        id: value.id,
        age: value.age,
        status: from_candid_DonorStatus_n4(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        appointedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.appointedAt)),
        name: value.name,
        districtId: value.districtId,
        rejectedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.rejectedAt)),
        bloodGroup: value.bloodGroup,
        lastDonatedDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastDonatedDate)),
        patientName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.patientName)),
        areaId: value.areaId,
        areaManagerId: value.areaManagerId,
        tempRejectedUntil: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.tempRejectedUntil)),
        tempRejectedReason: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tempRejectedReason))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: bigint;
    toId: [] | [bigint];
    toRole: string;
    message: string;
    fromRole: string;
    fromId: bigint;
}): {
    id: bigint;
    createdAt: bigint;
    toId?: bigint;
    toRole: string;
    message: string;
    fromRole: string;
    fromId: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        toId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.toId)),
        toRole: value.toRole,
        message: value.message,
        fromRole: value.fromRole,
        fromId: value.fromId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AreaManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    areaId: bigint;
    passwordHash: string;
}): {
    id: bigint;
    status: AreaManagerStatus;
    contact: string;
    username: string;
    districtId: bigint;
    areaId: bigint;
    passwordHash: string;
} {
    return {
        id: value.id,
        status: from_candid_AreaManagerStatus_n10(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        username: value.username,
        districtId: value.districtId,
        areaId: value.areaId,
        passwordHash: value.passwordHash
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): DistrictManagerStatus {
    return "pending" in value ? DistrictManagerStatus.pending : "approved" in value ? DistrictManagerStatus.approved : "rejected" in value ? DistrictManagerStatus.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forwarded: null;
} | {
    pending: null;
} | {
    completed: null;
}): BloodRequestStatus {
    return "forwarded" in value ? BloodRequestStatus.forwarded : "pending" in value ? BloodRequestStatus.pending : "completed" in value ? BloodRequestStatus.completed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appointed: null;
} | {
    tempRejected: null;
} | {
    available: null;
} | {
    permRejected: null;
}): DonorStatus {
    return "appointed" in value ? DonorStatus.appointed : "tempRejected" in value ? DonorStatus.tempRejected : "available" in value ? DonorStatus.available : "permRejected" in value ? DonorStatus.permRejected : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AreaManagerDto>): Array<AreaManagerDto> {
    return value.map((x)=>from_candid_AreaManagerDto_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DistrictManagerDto>): Array<DistrictManagerDto> {
    return value.map((x)=>from_candid_DistrictManagerDto_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodRequestDto>): Array<BloodRequestDto> {
    return value.map((x)=>from_candid_BloodRequestDto_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorDto>): Array<DonorDto> {
    return value.map((x)=>from_candid_DonorDto_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoticeDto>): Array<NoticeDto> {
    return value.map((x)=>from_candid_NoticeDto_n33(_uploadFile, _downloadFile, x));
}
function to_candid_DonorStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorStatus): _DonorStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amId?: bigint;
    userId?: bigint;
    dmId?: bigint;
    name: string;
    role: string;
}): {
    amId: [] | [bigint];
    userId: [] | [bigint];
    dmId: [] | [bigint];
    name: string;
    role: string;
} {
    return {
        amId: value.amId ? candid_some(value.amId) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        dmId: value.dmId ? candid_some(value.dmId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorStatus): {
    appointed: null;
} | {
    tempRejected: null;
} | {
    available: null;
} | {
    permRejected: null;
} {
    return value == DonorStatus.appointed ? {
        appointed: null
    } : value == DonorStatus.tempRejected ? {
        tempRejected: null
    } : value == DonorStatus.available ? {
        available: null
    } : value == DonorStatus.permRejected ? {
        permRejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
